= Logging
:figures: 13-logging

To properly maintain a distributed system like your microservice architecture,
you need a central place where you can access all the aggregated logs and search across them.

In Microservice architecture the application consists of multiple services and service instances that are running on multiple machines. Each service instance generates information about what it is doing to a log file in a standardized format. The log file might contains errors, warnings, information and debug messages.

To understand the behavior of an application and troubleshoot problems we should use a centralized logging service. The centralized logging aggregates logs from each service instance. When required the developer can search and analyze the logs.

We can also configure alerts that are triggered when certain messages appear in the logs.

But at the same time handling a large volume of logs requires substantial infrastructure.

Basically, the idea is to send all the log outputs from your applications to another
component in your system, which will consume them and put them all together. Besides,
you want to persist these logs for some time, so this component should have data
storage. Ideally, you should be able to navigate through these logs, search, and filter out
messages per microservice, instance, class, and so on. To do this, many of these tools
offer a user interface that connects to the aggregated logs storage

A common best practice when implementing the centralized logging approach is
to keep the application logic unaware of this pattern. The services should just output
messages using a common interface (e.g., a Logger in Java). The logging agent that
channels these logs to the central aggregator works independently, capturing the output
that the application produces.

== Examples
* https://github.com/spring-kb/logging-spring-rabbitmq-logging[A Simple Solution for Log Centralization Using Spring and RabbitMQ]