= SOLID
:figures: 11-development/00-software-development/oop

SOLID stands for five software development design principles intended to make software 
designs more flexible and maintainable: 

-  S: Single responsibility principle (SRP)
-  O: Open/Closed principle (OCP)
-  L: Liskov substitution principle (LSP)
-  I: Interface segregation principle (ISP)
-  D: Dependency inversion principle (DIP)

These principles were introduced by Robert C. Martin (Uncle Bob) and are widely used in object-oriented programming to create systems that are easier to understand, extend, and maintain.

Here is a brief overview of each of these principles:

-  SRP states that a class should have only one reason to change. A class should 
have only one job, and it should do it well.
-  OCP states that software entities (classes, modules, functions, etc.) should be 
open for extension but closed for modification. 
-  LSP states that objects of a superclass should be replaceable with objects of a 
subclass without affecting the correctness of the program. What works with a superclass should also work with its subclasses.
-  ISP states that a client should not be forced to depend on methods it does not use. 
It’s better to have small interfaces than big ones.
-  DIP states that high-level modules should not depend on low-level modules. You 
should program to interfaces, not implementations.


== Single responsibility

== Open--closed

== Liskov substitution

== Interface segregation

=== Real World Examples

* In Spring Security ,As part of user management, we use the *UserDetailsService* and *UserDetailsManager* interfaces. The UserDetailsService is only responsible for retrieving the user by username. This action is the only one needed by the framework to complete authentication. The UserDetailsManager adds behavior that refers to adding, modifying, or deleting the user, which is a required functionality in most applications. The separation between the two contracts is an excellent example of the interface segregation principle. Separating the interfaces allows for better flexibility because the framework doesn't force you to implement behavior if your app doesn't need it. If the app only
needs to authenticate the users, then implementing the UserDetailsService contract is enough to cover the desired functionality. To manage the users, UserDetailsService and the UserDetailsManager components need a way to represent them.

== Dependency inversion
