= Spring Messaging
:figures: 11-development/02-spring/05-message

Spring provides broad support for the most-used messaging solutions. The Spring
Framework itself has built-in support for the Java Message Service (JMS) API. The
Spring AMQP project (https://spring.io/projects/spring-amqp) adds support for this
messaging protocol and provides integration with RabbitMQ. 
The Spring for Apache Kafka
project (https://spring.io/projects/spring-kafka) provides that integration.

== Message converters

Supported  Spring AMQP message converters:

=== Java object serializer

. It's not a proper standard that you can use between programming
languages. If you introduced a consumer that's not written in Java,
you would have to look for a specific library to perform cross-
language deserialization.
. It uses a hard-coded, fully qualified type name in the header of the
message. The deserializer expects the Java bean to be located in the
same package and to have the same name and fields. This is not
flexible at all, since you may want to deserialize only some properties
and keep your own version of the event data, following good domain-
driven design practices.

=== JSON

On the subscriber side, you can benefit from the popularity of the JSON format to deserialize the contents using any programming language. You could also use your own object representation and ignore properties you don't need on the consumer side, thereby reducing the coupling between microservices. If the publisher includes new fields in the payload, the subscribers don't need to change anything.
By injecting a bean of type Jackson2JsonMessageConverter, you're overriding the
default Java object serializer by a JSON object serializer

[,java]
----
    @Bean
    public Jackson2JsonMessageConverter producerJackson2MessageConverter() {

        return new Jackson2JsonMessageConverter();
    }
----

The Jackson2JsonMessageConverter uses a Jackson's ObjectMapper preconfigured
in Spring AMQP. This bean will be used then by the RabbitTemplate implementation,
the class that serializes and sends objects as AMQP messages to the broker

=== XML

=== Google's Protocol Buffers (aka, protobuf)

In real systems where performance is critical, you should consider an efficient binary format (e.g., protobuf).

== Making messaging resilient to failures
Event-driven architectures solve some issues affecting synchronous request/response
interactions. For example, if you remove the temporal coupling between applications,
you won’t need to adopt patterns like circuit breakers, since the communication will
be asynchronous. If the consumer is momentarily unavailable while the producer
sends a message, it doesn’t matter. The consumer will receive the message once it’s up
and running again.

In software engineering, there are no silver bullets. Everything comes at a cost. On
the one hand, applications that are decoupled can operate more independently. On
the other hand, you introduced a new component in your system that needs to be
deployed and maintained: the message broker.

Assuming that part is taken care of by the platform, there’s still something for you to
do as the application developer. When an event happens and your application wants to
publish a message, something might go wrong. Retries and timeouts are still helpful, but
this time we’ll use them to make the interaction between application and broker more
resilient. 

For RabbitMQ check 10-message-queuing/RabbitMQ
For Spring Cloud Stream check  11-development/02-spring/09-spring-cloud/spring-cloud-stream/index