= OAuth 2
:figures: 09-security

OAuth 2.0 is a protocol for authorization, it does not cover authentication.

There are four roles defined in OAuth 2.0:

* *Resource owner*: This is typically the end user that owns the resources an application
wants to access.
* *Resource server*: This is the service hosting the protected resources.
* *Client*: This is the application that would like to access the resource.
* *Authorization server*: This is the server issuing access to the client, which is the role of Keycloak,Openam,etc.

== Scopes
Both ID Tokens and Access Tokens can include different information about the user,
which is formatted as claims in the JWT. Claims are simple key/value pairs in JSON for-
mat. For example, OpenID Connect defines several standard claims to carry informa-
tion about the user, like given_name, family_name, preferred_username, and email.

Access to such claims is controlled through scopes, a mechanism provided by
OAuth2 to limit what data an OAuth2 Client can access. You can think of scopes as
roles assigned to applications rather than to users. 

Scopes are an OAuth2 concept for limiting an application’s access to user
resources. You can think of them as roles, but for applications instead of users. 

Perhaps you have logged in to a third-party website using GitHub or Google (a
social login based on OAuth2). If you did, you might have noticed that right after
the authentication step, the service prompted you with a second request about
what information from your GitHub or Google account you consented to allow the
third party to access. That consent functionality is based on scopes, granting the third
party (the OAuth2 Client) specific permissions depending on what scopes have been
assigned.

When we use the OpenID Connect extension on top of OAuth2 to verify the user’s identity, we need to include the openid scope to inform the Authorization Server and receive an ID Token containing data about the user authentication.

== OAuth 2 Flows(Grant Types)

In an OAuth 2.0 protocol flow, the client requests access to a resource on behalf of a resource owner from the authorization server. The authorization server issues limited access to the resource in the form of an access token. After receiving the access token, the client can access the resource at the resource server by including the access token in the request.

There are two client types, which are confidential and public clients.

* Confidential clients are applications such as server-side web applications that are able to safely store credentials, which they can use to authenticate with the authorization server.
* Public clients, on the other hand, are client-side applications that are not able to safely store credentials.

As public clients are not able to authenticate with the authorization server, there are two safeguards in place:

* The authorization server will only send the authorization code to an application hosted on a pre-configured URL, in the form of a previously registered redirect URI.
* Proof Key for Code Exchange (PKCE, RFC 7636), which is an extension to OAuth 2.0, prevents anyone that intercepts an authorization code from exchanging it for an access token.

Depending on the application type and use case, there are a number of different flows that can be used. To help you decide what flow type you should use for your application, you can use the following simple formula:

* If the application accesses the resource on behalf of itself (the application is the resource owner), use the Client Credentials flow.
* If the application runs on a device without a browser or is input-constrained, use the Device flow. This could, for example, be a smart TV where it would be difficult for the user to enter the username and password.
* If none of the preceding conditions are applicable, use the authorization code flow.

== Tokens
as the resource servers are  able to directly read the value of the access token,
they do not always have to make a request to the OAuth 2.0 token introspection endpoint, or the OpenID Connect UserInfo endpoint. This potentially eliminates two additional requests to Aauth2 server for a request to the resource server, reducing latency as well as significantly reducing the number of requests to server.

When a resource server receives an access token, it is able to verify the token in the following ways:

* Retrieving the JWKS URL from the OpenID Connect Discovery endpoint(the OpenID Connect Discovery endpoint advertises an endpoint where the JSON Web Key Set (JWKS) can be retrieved, as well as what signing and encryption mechanisms from the JWA specification are supported).
* Downloading the public signing keys for the OP from the JWKS URL endpoint. These are
typically cached/stored at the Resource Server.
* Verifying the signature of the token using the public signing keys from the OP.

Access Tokens defined as JWTs should be handled with care. They
are bearer tokens, meaning that any application can use them in an HTTP
request and get access to an OAuth2 Resource Server. Handling the OIDC/
OAuth2 flow in the backend rather than in an SPA provides better security
because we don’t expose any tokens to the browser. However, there might be
other risks to manage, so carefully consider the trust boundaries of your system.