= Spring Cloud Kubernetes

Spring Cloud Kubernetes (https://spring.io/projects/spring-cloud-kubernetes) is
a project that provides Spring Boot integration with the Kubernetes API. Its
original goal was to make it easier to transition from a microservices architecture
based on Spring Cloud to Kubernetes. It provides an implementation for standard
Spring Cloud interfaces used for service discovery and load balancing to integrate
with Kubernetes, and it adds support for loading configuration from ConfigMaps
and Secrets.

If you work on a greenfield project!footnote:[A greenfield project is one that is started from scratch, without any constraints or dependencies on existing systems or infrastructure. The term originates from real estate, where it signifies construction on vacant land, free from prior development.], you don’t need Spring Cloud Kubernetes.
Kubernetes provides service discovery and load balancing natively. Furthermore, Spring Boot supports configuration via ConfigMaps and Secrets natively, so there’s no need for Spring Cloud Kubernetes, even in this case.

When migrating a brownfield project!footnote:[Brownfield development is a term commonly used in the information technology industry to describe problem spaces needing the development and deployment of new software systems in the immediate presence of existing (legacy) software applications/systems. This implies that any new software architecture must take into account and coexist with live software already in situ.] to Kubernetes, and it uses libraries like
Spring Cloud Netflix Eureka for service discovery and Spring Cloud Netflix Ribbon or
Spring Cloud Load Balancer for load balancing, you might use Spring Cloud Kubernetes for a smoother transition. However, It's recommended refactoring your code
to leverage the native service discovery and load-balancing features from Kubernetes
rather than adding Spring Cloud Kubernetes to your project.

The main reason why It's not recommended using Spring Cloud Kubernetes in standard applications is that it requires access to the Kubernetes API Server to manage
Pods, Services, ConfigMaps, and Secrets. Besides the security concerns related to
granting applications access to the Kubernetes internal objects, it would also couple
the applications to Kubernetes unnecessarily and affect the maintainability of the
solution.

When does it make sense to use Spring Cloud Kubernetes? 
 
- As one example, Spring
Cloud Gateway could be enhanced with Spring Cloud Kubernetes to get more control
over service discovery and load balancing, including automatic registration of new
routes based on Services metadata and the choice of load-balancing strategy. In this
case, you could rely on the Spring Cloud Kubernetes Discovery Server component,
limiting the need for Kubernetes API access to the discovery server.
- Spring Cloud Kubernetes really shines when it comes to implementing Kubernetes
controller applications to accomplish administrative tasks within the cluster. For example, you could implement a controller that monitors when ConfigMaps or Secrets change and then triggers a configuration refresh on the application using them. As a
matter of fact, the Spring team used Spring Cloud Kubernetes to build a controller
that does precisely that: the Configuration Watcher.

== Spring Cloud Kubernetes Config Server
Besides the Configuration Watcher, Spring Cloud Kubernetes provides other convenient off-the-shelf applications for addressing common concerns of distributed systems in Kubernetes. One of them is a configuration server built on top of Spring
Cloud Config and extending its functionality to support reading configuration data
from ConfigMaps and Secrets. It’s called Spring Cloud Kubernetes Config Server.

You can use this application directly (the container image is published on Docker
Hub) and deploy it on Kubernetes following the instructions provided in the official
documentation (https://spring.io/projects/spring-cloud-kubernetes).

As an alternative, you can use its source code on GitHub as a foundation to build
your own Kubernetes-aware configuration server. For example, you might want to protect it via HTTP Basic authentication. In that
case, you could use your experience working with Spring Cloud Config and build an
enhanced version of Config Service on top of Spring Cloud Kubernetes Config Server.