= Testing Spring Cloud Stream
The framework provides a binder specifically for implementing integration tests
focusing on the business logic rather than the middleware.

First, you need to add a test dependency on Reactor Test
[source,gradle,attributes]
----
dependencies {
	testImplementation 'org.springframework.cloud:spring-cloud-stream-test-binder'
}
----
[source,xml,attributes]
----
<dependency>
	<groupId>org.springframework.cloud</groupId>
	<artifactId>spring-cloud-stream-test-binder</artifactId>
	<scope>test</scope>
</dependency>
----


== Writing integration tests with @FunctionalSpringBootTest
The test setup consists of three steps:

1 Import the TestChannelBinderConfiguration class providing configuration
for the test binder.

2 Inject an InputDestination bean representing the input binding packlabelin-0 (by default, since it’s the only one).

3 Inject an OutputDestination bean representing the output binding packlabelout-0 (by default, since it’s the only one).


[source,java,attributes]
----
public record OrderAcceptedMessage (
		Long orderId
){}
//DTO containing the order identifier as a Long field
public record OrderDispatchedMessage (
		Long orderId
){}

@Configuration
public class DispatchingFunctions {

	private static final Logger log = LoggerFactory.getLogger(DispatchingFunctions.class);

	@Bean
	public Function<OrderAcceptedMessage, Long> pack() {
		return orderAcceptedMessage -> {
			log.info("The order with id {} is packed.", orderAcceptedMessage.orderId());
			return orderAcceptedMessage.orderId();
		};
	}

	@Bean
	public Function<Flux<Long>, Flux<OrderDispatchedMessage>> label() {
		return orderFlux -> orderFlux.map(orderId -> {
			log.info("The order with id {} is labeled.", orderId);
			return new OrderDispatchedMessage(orderId);
		});
	}

}
----
The data flow is based on Message objects (from the org.springframework.messaging package). The framework handles type conversion for you transparently when
running the application. However, in this type of test, you need to provide Message
objects explicitly. You can use MessageBuilder to create the input message, and use
the ObjectMapper utility to perform the type conversion from the binary format used
for storing message payloads in a broker.

Message brokers like RabbitMQ deal with binary data, so any data flowing through
them is mapped to byte[] in Java. The conversion between bytes and DTOs is handled by Spring Cloud Stream transparently. But just like for messages, we need to
handle that explicitly in this test scenario when asserting the content of the message
received from the output channel.
[source,java,attributes]
----
import java.io.IOException;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.stream.binder.test.InputDestination;
import org.springframework.cloud.stream.binder.test.OutputDestination;
import org.springframework.cloud.stream.binder.test.TestChannelBinderConfiguration;
import org.springframework.context.annotation.Import;
import org.springframework.integration.support.MessageBuilder;
import org.springframework.messaging.Message;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@Import(TestChannelBinderConfiguration.class)
class FunctionsStreamIntegrationTests {

    @Autowired
    private InputDestination input;

    @Autowired
    private OutputDestination output;

    @Autowired
    private ObjectMapper objectMapper;

    @Test
    void whenOrderAcceptedThenDispatched() throws IOException {
        long orderId = 121;
        Message<OrderAcceptedMessage> inputMessage = MessageBuilder
                .withPayload(new OrderAcceptedMessage(orderId)).build();
        Message<OrderDispatchedMessage> expectedOutputMessage = MessageBuilder
                .withPayload(new OrderDispatchedMessage(orderId)).build();

        this.input.send(inputMessage);
        assertThat(objectMapper.readValue(output.receive().getPayload(), OrderDispatchedMessage.class))
                .isEqualTo(expectedOutputMessage.getPayload());
    }

}
----
== Testing RabbitMQ
 If you want to test the application against a specific broker (in
our case, it would be for RabbitMQ), you can rely on Testcontainers, 