= Postgres
:figures: 12-db/sql

== Self-Managed
=== Running a PostgreSQL Database

Run PostgreSQL as a Docker container

[,bash]
----
docker run -d \
    --name polar-postgres \
    -e POSTGRES_USER=user \
    -e POSTGRES_PASSWORD=password \
    -e POSTGRES_DB=polardb_catalog \
    -p 5432:5432 \
    postgres:14.12
----

stop the container
[,bash]
----
docker stop polar-postgres 
----
start it again with 
[,bash]
----
docker start polar-postgres. 
----
If you want to
start over, you can remove the container with 
[,bash]
----
docker rm -fv polar-postgres
----
and create it again with the previous docker run command. 

=== Database Commands

Start an interactive PSQL console:

[,bash]
----
docker exec -it polar-postgres psql -U user -d polardb_catalog
----

|===
| PSQL Command | Description

| `\list`
| List all databases.

| `\connect polardb_catalog`
| Connect to specific database.

| `\dt`
| List all tables.

| `\d book`
| Show the `book` table schema.

| `\quit`
| Quit interactive psql console.
|===

From within the PSQL console, you can also fetch all the data stored in the `book` table.

[,bash]
----
select * from book;
----

== Cloud Based
=== Azure Database for PostgreSQL
=== Amazon RDS for PostgreSQL
=== Google Cloud SQL for PostgreSQL
=== Alibaba Cloud ApsaraDB RDS for PostgreSQL
=== DigitalOcean PostgreSQL