= Data structures and Algorithms
:figures: 11-development/00-software-development/data-structures-and-algorithms/algorithms

== Algorithms

An algorithm is a set of logical instructions to perform a particular task.

An algorithm can be seen as a roadmap or a set of instructions to accomplish a well-defined task.

The common examples of algorithms include traffic lights
regulating congestion on the streets, face recognition software on
smartphones, recommendation technologies, and so on.
It's important for you to understand that an algorithm is just a small part
of an application used to solve a well-defined problem. Examples such
as sorting a list of numbers, finding the shortest route, or word prediction
are all correct. Big software applications, such as email clients or an
operating system are improper examples.

=== Complexities

== Data structures

A data structure is a way of organizing data so that it can be accessed and/or modified efficiently.

== Links
* https://www.programiz.com/java-programming/examples